public enum GCMicroGamepadElementType
{
    ButtonA,
    ButtonX,
    ButtonMenu,
    DPad,
    DPadX,
    DPadY,
    DPadLeft,
    DPadRight,
    DPadUp,
    DPadDown,
    DPadRing,
    DPadRingLeft,
    DPadRingRight,
    DPadRingUp,
    DPadRingDown,
    DPadRingX,
    DPadRingY
}